/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.project;

/**
 *
 * @author Aniruddh
 */
public class DelhiWaitListPage extends javax.swing.JFrame {

    /**
     * Creates new form WaitListPage
     */
    public DelhiWaitListPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        itcMauryaBtn = new javax.swing.JLabel();
        itcWLBtn = new javax.swing.JButton();
        itcPerNightLbl = new javax.swing.JLabel();
        itcPerNightLbl1 = new javax.swing.JLabel();
        itcTotalCostLbl = new javax.swing.JLabel();
        itcTotalCostLbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        checkOUTLbl = new javax.swing.JLabel();
        checkOUTLbl1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ashokaLbl = new javax.swing.JLabel();
        ashokaWLBtn = new javax.swing.JButton();
        ashokaPerNightLbl1 = new javax.swing.JLabel();
        ashokaTotalCostLbl1 = new javax.swing.JLabel();
        ashokaPerNightLbl = new javax.swing.JLabel();
        ashokaTotalCostLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        noOfRoomsLbl = new javax.swing.JLabel();
        noOfRoomsLbl1 = new javax.swing.JLabel();
        UserNameLbl = new javax.swing.JLabel();
        noOfDaysLbl = new javax.swing.JLabel();
        placeLbl1 = new javax.swing.JLabel();
        noOfDaysLbl1 = new javax.swing.JLabel();
        placeLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radisonLbl = new javax.swing.JLabel();
        radisonWLBtn = new javax.swing.JButton();
        radisonPerNightLbl = new javax.swing.JLabel();
        radisonPerNightLbl1 = new javax.swing.JLabel();
        radisonTotalCostLbl = new javax.swing.JLabel();
        radisonTotalCostLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        UserNameLbl1 = new javax.swing.JLabel();
        checkINLbl = new javax.swing.JLabel();
        checkINLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itcMauryaBtn.setText("Hotel ITC Maurya");

        itcWLBtn.setText("Enroll in Wait List");
        itcWLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itcWLBtnActionPerformed(evt);
            }
        });

        itcPerNightLbl.setText("Per Night Cost :");

        itcPerNightLbl1.setText("Rs.14000");

        itcTotalCostLbl.setText("Total Cost of your Stay : ");

        itcTotalCostLbl1.setText("UserDefinedText");

        jLabel2.setText("Rs.");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/itc1.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/itc2.jpg"))); // NOI18N
        jLabel7.setText("jLabel4");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setText("Amenities :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("5 Star");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("690 Feedbacks");

        jLabel16.setText("1. Free WIFI");

        jLabel17.setText("2. Complimentary breakfast");

        jLabel18.setText("3. Pool side bar");

        jLabel23.setText("4. Spa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itcMauryaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(itcWLBtn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itcPerNightLbl)
                                .addGap(18, 18, 18)
                                .addComponent(itcPerNightLbl1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itcTotalCostLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itcTotalCostLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel21)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel22))
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itcMauryaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itcWLBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itcPerNightLbl)
                    .addComponent(itcPerNightLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itcTotalCostLbl)
                    .addComponent(itcTotalCostLbl1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        checkOUTLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkOUTLbl.setText("CheckOUT :");

        checkOUTLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        checkOUTLbl1.setText("UserDefinedDate");

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        ashokaLbl.setText("Hotel Ashoka");

        ashokaWLBtn.setText("Enroll in Wait List");
        ashokaWLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ashokaWLBtnActionPerformed(evt);
            }
        });

        ashokaPerNightLbl1.setText("Rs.10000");

        ashokaTotalCostLbl1.setText("UserDefinedText");

        ashokaPerNightLbl.setText("Per Night Cost :");

        ashokaTotalCostLbl.setText("Total Cost of your Stay : ");

        jLabel1.setText("Rs.");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ashoka2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ashoka1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Amenities :");

        jLabel11.setText("1. Free WIFI");

        jLabel12.setText("2. Complimentary breakfast");

        jLabel13.setText("3. Pool side bar");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("4.5 Star");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("670 Feedbacks");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("670 Feedbacks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ashokaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(ashokaWLBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ashokaPerNightLbl)
                        .addGap(18, 18, 18)
                        .addComponent(ashokaPerNightLbl1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ashokaTotalCostLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ashokaTotalCostLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel19)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel14))
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(565, 565, 565)
                    .addComponent(jLabel20)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ashokaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ashokaWLBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ashokaPerNightLbl1)
                    .addComponent(ashokaPerNightLbl))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ashokaTotalCostLbl)
                    .addComponent(ashokaTotalCostLbl1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel20)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        noOfRoomsLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        noOfRoomsLbl.setText("No of Rooms :");

        noOfRoomsLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        noOfRoomsLbl1.setText("UserDefinedRooms");

        UserNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserNameLbl.setText("UserName : ");

        noOfDaysLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        noOfDaysLbl.setText("No of Days :");

        placeLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        placeLbl1.setText("UserDefinedPlace");

        noOfDaysLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        noOfDaysLbl1.setText("UserDefinedDays");

        placeLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        placeLbl.setText("Place          :");

        radisonLbl.setText("Hotel Radison Blu");

        radisonWLBtn.setText("Enroll in Wait List");
        radisonWLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radisonWLBtnActionPerformed(evt);
            }
        });

        radisonPerNightLbl.setText("Per Night Cost :");

        radisonPerNightLbl1.setText("Rs.5500");

        radisonTotalCostLbl.setText("Total Cost of your Stay : ");

        radisonTotalCostLbl1.setText("UserDefinedText");

        jLabel3.setText("Rs.");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radison1.jpg"))); // NOI18N
        jLabel8.setText("jLabel5");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radison2.jpg"))); // NOI18N
        jLabel9.setText("jLabel4");

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel24.setText("Amenities :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("4 Star");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("350 Feedbacks");

        jLabel27.setText("1. Free WIFI");

        jLabel28.setText("2. Complimentary breakfast");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radisonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(radisonWLBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radisonPerNightLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radisonPerNightLbl1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radisonTotalCostLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radisonTotalCostLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel26)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radisonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radisonWLBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radisonPerNightLbl)
                            .addComponent(radisonPerNightLbl1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radisonTotalCostLbl)
                            .addComponent(radisonTotalCostLbl1)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        UserNameLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        UserNameLbl1.setText("Dummy");

        checkINLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkINLbl.setText("CheckIN    :");

        checkINLbl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        checkINLbl1.setText("UserDefinedDate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkINLbl)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(checkOUTLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkINLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(checkOUTLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(placeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UserNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(UserNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(placeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(92, 92, 92)
                                    .addComponent(noOfDaysLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noOfDaysLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(noOfRoomsLbl)
                        .addGap(26, 26, 26)
                        .addComponent(noOfRoomsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameLbl)
                    .addComponent(UserNameLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeLbl1)
                    .addComponent(placeLbl)
                    .addComponent(noOfDaysLbl)
                    .addComponent(noOfDaysLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkINLbl)
                    .addComponent(checkINLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOUTLbl)
                    .addComponent(checkOUTLbl1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfRoomsLbl)
                    .addComponent(noOfRoomsLbl1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itcWLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itcWLBtnActionPerformed
        // TODO add your handling code here:
        WaitListPage b=new WaitListPage(UserNameLbl1.getText(),placeLbl1.getText(),"ITC Maurya",checkINLbl1.getText(),checkOUTLbl1.getText(),itcTotalCostLbl1.getText(),noOfRoomsLbl1.getText(),noOfDaysLbl1.getText());
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_itcWLBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        CompareHotels ch=new CompareHotels();
        ch.userName(UserNameLbl1.getText());
        ch.setVisible(true);
        dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    private void ashokaWLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ashokaWLBtnActionPerformed
        // TODO add your handling code here:
         WaitListPage b=new WaitListPage(UserNameLbl1.getText(),placeLbl1.getText(),"ASHOKA",checkINLbl1.getText(),checkOUTLbl1.getText(),ashokaTotalCostLbl1.getText(),noOfRoomsLbl1.getText(),noOfDaysLbl1.getText());
        b.setVisible(true);
        dispose();

    }//GEN-LAST:event_ashokaWLBtnActionPerformed

    private void radisonWLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radisonWLBtnActionPerformed
        // TODO add your handling code here:
        WaitListPage b=new WaitListPage(UserNameLbl1.getText(),placeLbl1.getText(),"Radison Blu",checkINLbl1.getText(),checkOUTLbl1.getText(),radisonTotalCostLbl1.getText(),noOfRoomsLbl1.getText(),noOfDaysLbl1.getText());
        b.setVisible(true);
        dispose();

    }//GEN-LAST:event_radisonWLBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelhiWaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelhiWaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelhiWaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelhiWaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelhiWaitListPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JLabel UserNameLbl1;
    private javax.swing.JLabel ashokaLbl;
    private javax.swing.JLabel ashokaPerNightLbl;
    private javax.swing.JLabel ashokaPerNightLbl1;
    private javax.swing.JLabel ashokaTotalCostLbl;
    private javax.swing.JLabel ashokaTotalCostLbl1;
    private javax.swing.JButton ashokaWLBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel checkINLbl;
    private javax.swing.JLabel checkINLbl1;
    private javax.swing.JLabel checkOUTLbl;
    private javax.swing.JLabel checkOUTLbl1;
    private javax.swing.JLabel itcMauryaBtn;
    private javax.swing.JLabel itcPerNightLbl;
    private javax.swing.JLabel itcPerNightLbl1;
    private javax.swing.JLabel itcTotalCostLbl;
    private javax.swing.JLabel itcTotalCostLbl1;
    private javax.swing.JButton itcWLBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel noOfDaysLbl;
    private javax.swing.JLabel noOfDaysLbl1;
    private javax.swing.JLabel noOfRoomsLbl;
    private javax.swing.JLabel noOfRoomsLbl1;
    private javax.swing.JLabel placeLbl;
    private javax.swing.JLabel placeLbl1;
    private javax.swing.JLabel radisonLbl;
    private javax.swing.JLabel radisonPerNightLbl;
    private javax.swing.JLabel radisonPerNightLbl1;
    private javax.swing.JLabel radisonTotalCostLbl;
    private javax.swing.JLabel radisonTotalCostLbl1;
    private javax.swing.JButton radisonWLBtn;
    // End of variables declaration//GEN-END:variables
public void changeLabels(String name,String place,String CheckIN,String CheckOUT,String noOfRooms,String numberOfDays)
{
    UserNameLbl1.setText(name);
    placeLbl1.setText(place);
    checkINLbl1.setText(CheckIN);
    checkOUTLbl1.setText(CheckOUT);
    noOfRoomsLbl1.setText(noOfRooms);
    noOfDaysLbl1.setText(numberOfDays);
    ashokaTotalCostLbl1.setText(String.valueOf(10000*Integer.parseInt(numberOfDays)*Integer.parseInt(noOfRooms)));
    itcTotalCostLbl1.setText(String.valueOf(14000*Integer.parseInt(numberOfDays)*Integer.parseInt(noOfRooms)));
    radisonTotalCostLbl1.setText(String.valueOf(5500*Integer.parseInt(numberOfDays)*Integer.parseInt(noOfRooms)));
    
    
}


}
