/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author Aniruddh
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        jDateChooserDOB.setMaxSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        newUserLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        userNameTxt2 = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxtArea = new javax.swing.JTextArea();
        emailIdLbl = new javax.swing.JLabel();
        emailIdTxt = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        regResponse = new javax.swing.JLabel();
        newUserPswdLbl = new javax.swing.JLabel();
        newUserPswd = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        jDateChooserDOB = new com.toedter.calendar.JDateChooser();

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel.setText("USER NAME");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newUserLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newUserLbl.setText("NEW USER");

        dobLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dobLbl.setText("DATE(YYYY-MM-DD)");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        userNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLbl.setText("USER NAME");
        userNameLbl.setMaximumSize(new java.awt.Dimension(53, 22));
        userNameLbl.setMinimumSize(new java.awt.Dimension(53, 22));

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLbl.setText("NAME");

        addressLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressLbl.setText("ADDRESS");

        addressTxtArea.setColumns(20);
        addressTxtArea.setRows(5);
        jScrollPane1.setViewportView(addressTxtArea);

        emailIdLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailIdLbl.setText("EMAIL ID");

        emailIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTxtActionPerformed(evt);
            }
        });

        regBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        newUserPswdLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newUserPswdLbl.setText("PASSWORD");

        newUserPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserPswdActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobLbl)
                                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailIdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(backBtn)
                                                .addGap(59, 59, 59)
                                                .addComponent(regBtn))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jDateChooserDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(userNameTxt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addComponent(newUserPswd, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newUserPswdLbl)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newUserPswdLbl)
                    .addComponent(newUserPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(regBtn))
                .addGap(32, 32, 32)
                .addComponent(regResponse)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        
        if(userNameTxt2.getText().length()==0 || nameTxt.getText().length()==0 || newUserPswd.getPassword().toString().length()==0 || addressTxtArea.getText().length()==0 ||emailIdTxt.getText().length()==0||jDateChooserDOB.getDate()==null)
        {
            JOptionPane.showMessageDialog(null,"Enter all the details for registration");
        }
        else
        {
            //Use of Regular Expression to match Email-id
            if(!(Pattern.matches("[a-z][a-z1-9\\_]*@{1}[a-z1-9\\_]*\\.{1}[a-z1-9\\_\\.]*", emailIdTxt.getText())))
            {
                JOptionPane.showMessageDialog(null,"Invalid Email Id");
                return ;
            }
            
            Connection con;
        
            try {
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
               // Date dob=jDateChooserDOB.getDate();
                String dobStr=sdf.format(jDateChooserDOB.getDate()).toString();
                Date dob=sdf.parse(dobStr);
                java.sql.Date sqlDateDOB = new java.sql.Date(dob.getTime());
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/usersdb","root","shantanu2003");
                String insertRow="INSERT INTO users(UserName,Name,DOB,Address,EmailID,Password)VALUES(?,?,?,?,?,?)";
                PreparedStatement statement=con.prepareStatement(insertRow);
                statement.setString(1,userNameTxt2.getText());
                statement.setString(2,nameTxt.getText());
                
                statement.setDate(3,sqlDateDOB);
                statement.setString(4,addressTxtArea.getText());
                statement.setString(5,emailIdTxt.getText());
                statement.setString(6,newUserPswd.getText());

                String query = "Select * from users where username ='"+userNameTxt2.getText()+"'";
                PreparedStatement check=con.prepareStatement(query);
                ResultSet rs=check.executeQuery();

                int rowsInserted;

                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"User Name already exist, please choose another username");
                }
                else
                {
                    rowsInserted=statement.executeUpdate();


                if(rowsInserted>0)
                {
                    //regResponse.setText("User Registred");
                    JOptionPane.showMessageDialog(null,"User Registered");
                    LoginPage l=new LoginPage();
                    l.setVisible(true);
                    dispose();
                }
                else
                    regResponse.setText("User Not Registred, Some Error Occured");


                }
            }

            catch (Exception e) {
                regResponse.setText("User Not Registred, Some Error Occured"+e);
            }
        }    
    }//GEN-LAST:event_regBtnActionPerformed

    private void newUserPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserPswdActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void emailIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextArea addressTxtArea;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JTextField emailIdTxt;
    private com.toedter.calendar.JDateChooser jDateChooserDOB;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel newUserLbl;
    private javax.swing.JPasswordField newUserPswd;
    private javax.swing.JLabel newUserPswdLbl;
    private javax.swing.JButton regBtn;
    private javax.swing.JLabel regResponse;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTextField userNameTxt2;
    // End of variables declaration//GEN-END:variables
}
