/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Aniruddh
 */
public class WaitListPage extends javax.swing.JFrame {

    /**
     * Creates new form BookingPage
     */
    
    
  //  public Date CIN=new Date();
   // public Date COUT=new Date();
    public String bookingID;
     DelhiBooking db;
     MumbaiBooking m;
     HyderabadBooking h;
     
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    public WaitListPage() {
        initComponents();
    }
    public WaitListPage(String userName,String place,String hotel,String checkIN,String checkOUT,String totalCost,String noOfRooms,String noOfDays)
    {
        
        initComponents();
        userNameLbl1.setText(userName);
        placeLbl1.setText(place);
        hotelLbl1.setText(hotel);
        checkINLbl1.setText(checkIN);
      
        
        noOfRoomsLbl1.setText(noOfRooms);
        
        checkOUTlbl1.setText(checkOUT);
        totalCostLbl1.setText(totalCost);
        noOfDaysLbl1.setText(noOfDays);
      
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        placeLbl = new javax.swing.JLabel();
        placeLbl1 = new javax.swing.JLabel();
        hotelLbl = new javax.swing.JLabel();
        hotelLbl1 = new javax.swing.JLabel();
        checkINLbl = new javax.swing.JLabel();
        checkINLbl1 = new javax.swing.JLabel();
        checkOUTLbl = new javax.swing.JLabel();
        checkOUTlbl1 = new javax.swing.JLabel();
        totalCostLbl = new javax.swing.JLabel();
        totalCostLbl1 = new javax.swing.JLabel();
        adharLbl = new javax.swing.JLabel();
        adharTxt = new javax.swing.JTextField();
        WLBtn = new javax.swing.JButton();
        userNameLbl = new javax.swing.JLabel();
        userNameLbl1 = new javax.swing.JLabel();
        noOfRoomsLbl = new javax.swing.JLabel();
        noOfRoomsLbl1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        noOfDaysLbl = new javax.swing.JLabel();
        noOfDaysLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Wait List Page");

        placeLbl.setText("Place");

        placeLbl1.setText("UserDefinedSpace");

        hotelLbl.setText("Hotel ");

        hotelLbl1.setText("UserDefinedHotel");

        checkINLbl.setText("CheckIN");

        checkINLbl1.setText("UserDefinedCheckIN");

        checkOUTLbl.setText("CheckOUT");

        checkOUTlbl1.setText("UserDefinedCheckOUT");

        totalCostLbl.setText("Totlal Cost of Stay");

        totalCostLbl1.setText("UserDefinedTotalCost");

        adharLbl.setText("Adhar No./Pans Card No.");

        adharTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharTxtActionPerformed(evt);
            }
        });

        WLBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WLBtn.setText("Enroll");
        WLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WLBtnActionPerformed(evt);
            }
        });

        userNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLbl.setText("User Name :");

        userNameLbl1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        userNameLbl1.setText("Dummy");

        noOfRoomsLbl.setText("No.of Rooms");

        noOfRoomsLbl1.setText("UserDefined");

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        noOfDaysLbl.setText("Number of Days :");

        noOfDaysLbl1.setText("UserDefinedNumber");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adharLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(WLBtn)
                        .addGap(88, 88, 88)
                        .addComponent(backBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noOfRoomsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(placeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hotelLbl)
                                    .addComponent(checkINLbl)
                                    .addComponent(checkOUTLbl)
                                    .addComponent(totalCostLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(noOfRoomsLbl1)
                                            .addComponent(adharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(placeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(checkOUTlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(checkINLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(hotelLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(totalCostLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(111, 111, 111)
                                                .addComponent(noOfDaysLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(noOfDaysLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(70, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLbl)
                    .addComponent(userNameLbl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeLbl1)
                    .addComponent(noOfDaysLbl)
                    .addComponent(noOfDaysLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelLbl)
                    .addComponent(hotelLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkINLbl)
                    .addComponent(checkINLbl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOUTLbl)
                    .addComponent(checkOUTlbl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostLbl)
                    .addComponent(totalCostLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfRoomsLbl)
                    .addComponent(noOfRoomsLbl1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adharLbl)
                    .addComponent(adharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WLBtn)
                    .addComponent(backBtn))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adharTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharTxtActionPerformed
        // TODO add your handling code here:
        
        if(adharTxt.getText().length()!=0)
            WLBtn.setEnabled(true);
        else
            WLBtn.setEnabled(false);
        
    }//GEN-LAST:event_adharTxtActionPerformed

    private void WLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WLBtnActionPerformed
        // TODO add your handling code here:
        
        if(adharTxt.getText().length()!=0)
        {
            
            try {
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/usersdb","root","shantanu2003"); 
               String query="INSERT INTO waitlist VALUES(?,?,?,?,?,?,?,?,?,?)";
               PreparedStatement stmt=con.prepareStatement(query);

               Random rnd=new Random();
               bookingID=Integer.toString(rnd.nextInt(1000000)+1);
               stmt.setString(1, userNameLbl1.getText());
               stmt.setString(2, placeLbl1.getText());
               stmt.setString(3, hotelLbl1.getText());

               Date CIN =sdf.parse(checkINLbl1.getText());
               Date COUT=sdf.parse(checkOUTlbl1.getText());
               java.sql.Date sqlDateCIN = new java.sql.Date(CIN.getTime());
               java.sql.Date sqlDateCOUT = new java.sql.Date(COUT.getTime());




               stmt.setDate(4, sqlDateCIN);
               stmt.setDate(5, sqlDateCOUT);
               stmt.setInt(6, Integer.parseInt(noOfRoomsLbl1.getText()));

               stmt.setString(7, bookingID);
               stmt.setString(8,adharTxt.getText());
               stmt.setString(9, totalCostLbl1.getText());
               stmt.setTimestamp(10, new Timestamp(System.currentTimeMillis()));



               int rowInserted;

               rowInserted=stmt.executeUpdate();



               //JOptionPane.showMessageDialog(null,"Booking Confirmed \n BookingID:"+bookingID);

                if( rowInserted>0)
                {
                 JOptionPane.showMessageDialog(null,"Enrollment done \n BookingID:"+bookingID);
                 CompareHotels ch =new CompareHotels();
                 ch.userName(userNameLbl1.getText());
                 ch.setVisible(true);
                 dispose();
                 
                }
                else 
                {
                     JOptionPane.showMessageDialog(null,"Enrollement Not Done");
                }


            } catch (Exception e) {

                JOptionPane.showMessageDialog(null,e);
            }

        
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Please give your Adhar/Pan Card Number");
        }
        
        
    }//GEN-LAST:event_WLBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        if(placeLbl1.getText()=="DELHI")
        {
            DelhiWaitListPage db=new DelhiWaitListPage();
            db.changeLabels(userNameLbl1.getText(), placeLbl1.getText(),checkINLbl1.getText(), checkOUTlbl1.getText(), noOfRoomsLbl1.getText(), noOfDaysLbl1.getText());
            db.setVisible(true);
            dispose();           
        }
        if(placeLbl1.getText()=="MUMBAI")
        {
            //MumbaiBooking m=new MumbaiBooking();
            m.changeLabels(userNameLbl1.getText(), placeLbl1.getText(),checkINLbl1.getText(), checkOUTlbl1.getText(), noOfRoomsLbl1.getText(), noOfDaysLbl1.getText());
            m.setVisible(true);
            dispose();           
        }
        
        if(placeLbl1.getText()=="HYDERABAD")
        {
           //MumbaiBooking m=new MumbaiBooking();
           h.changeLabels(userNameLbl1.getText(), placeLbl1.getText(),checkINLbl1.getText(), checkOUTlbl1.getText(), noOfRoomsLbl1.getText(), noOfDaysLbl1.getText());
           h.setVisible(true);
           dispose();  
            
        }
        
        
        
        
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaitListPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaitListPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton WLBtn;
    private javax.swing.JLabel adharLbl;
    private javax.swing.JTextField adharTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel checkINLbl;
    private javax.swing.JLabel checkINLbl1;
    private javax.swing.JLabel checkOUTLbl;
    private javax.swing.JLabel checkOUTlbl1;
    private javax.swing.JLabel hotelLbl;
    private javax.swing.JLabel hotelLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel noOfDaysLbl;
    private javax.swing.JLabel noOfDaysLbl1;
    private javax.swing.JLabel noOfRoomsLbl;
    private javax.swing.JLabel noOfRoomsLbl1;
    private javax.swing.JLabel placeLbl;
    private javax.swing.JLabel placeLbl1;
    private javax.swing.JLabel totalCostLbl;
    private javax.swing.JLabel totalCostLbl1;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JLabel userNameLbl1;
    // End of variables declaration//GEN-END:variables
}
